[package]
name = "data-sensors"
version = "0.1.0"
authors = ["Ja <ja@mail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.82"

[[bin]]
name = "data-sensors"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice, and they don't increase the size on Flash
opt-level = "z"

[dependencies]
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"

esp-idf-svc = "0.51"
esp-idf-hal = "0.45.2"
esp-idf-sys = "0.36.1"

# Remove `generic-queue-8` if you plan to use `embassy-time` WITH `embassy-executor`
embassy-time = { version = "0.5", features = ["generic-queue-8"] }

embedded-graphics = "0.8.1"
ssd1306 = "0.10.0"
display-interface-spi = "0.5.0"

anyhow = "1.0.100"
log = "0.4"
chrono = { version = "0.4.44", features = ["serde"]}
dotenvy = "0.15.7"

sqlx = { version = "0.9.0", features = ["runtime-tokio", "mysql", "chrono"] }

[build-dependencies]
embuild = "0.33"